### ISSUE TITLE
/downloads.html 500 internal error

### ISSUE THREAD

**Issue by Froxcey** [jetzig-framework/jetzig.dev#2]
Go to https://www.jetzig.dev/downloads.html and see the error. I unfortunately don't have any detail, look for the server log or something idk.

<img src="https://github.com/Avdan-OS/Compositor/assets/51555391/d0379882-f2dc-42e1-962f-b3f122db656f" alt="vibe" width="60"/>

**Comment by bobf** [comment]
Fixed ! Thanks a lot.

**Comment by bobf** [comment]
Closing.
